# Workflow that triggers when commits are pushed to PRs

on:
  pull_request:
    types: [synchronize]

jobs:
  test-install-python-version:
    uses: ./.github/workflows/test-install.yml
    with:
      versions: '["3.10", "3.11", "3.12"]'
      lint: true
      pytest: true

  build-package:
    uses: ./.github/workflows/build-package.yml
    with:
      artifact-name: "package-dist"

  
